"""Post weekly valuation report to WordPress.com via REST API.

Uses Application Password authentication (no token expiry).
Posts US-market companies only, in English.

Env vars: WP_SITE_URL, WP_USERNAME, WP_APP_PASSWORD
"""

from __future__ import annotations

import argparse
import json
import logging
import os
from base64 import b64encode
from pathlib import Path
from urllib.parse import urlparse

import requests

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "\n\n---\n\n"
    "*This report is auto-generated by an AI-based valuation pipeline "
    "and does not constitute investment advice. "
    "Please conduct your own due diligence before making investment decisions.*"
)


def _get_credentials() -> tuple[str, str, str]:
    """Return (site_url, username, app_password) from env."""
    site_url = os.getenv("WP_SITE_URL", "").rstrip("/")
    username = os.getenv("WP_USERNAME", "")
    password = os.getenv("WP_APP_PASSWORD", "")
    return site_url, username, password


def _auth_header(username: str, password: str) -> dict[str, str]:
    """Build Basic auth header for WordPress Application Password."""
    token = b64encode(f"{username}:{password}".encode()).decode()
    return {"Authorization": f"Basic {token}"}


def _build_post_content(summary: dict) -> str:
    """Build HTML blog post body from weekly summary (US companies only).

    Uses the existing summary_md fields from valuation entries.
    """
    import markdown
    import re as _re

    valuations = summary.get("valuations", [])
    discoveries = summary.get("discoveries", [])

    # Filter US-only valuations
    us_valuations = [
        v
        for v in valuations
        if v.get("market") == "US" and v.get("status") == "success"
    ]

    if not us_valuations:
        return ""

    # Build markdown content
    lines = [
        "## Market Overview\n",
    ]

    # Discovery summary for US
    for d in discoveries:
        if d.get("market") == "US":
            news_count = d.get("news_count", 0)
            cos = d.get("companies", [])
            co_names = ", ".join(c.get("name", "") for c in cos[:5])
            lines.append(f"- **News collected**: {news_count} articles\n")
            lines.append(f"- **Companies discovered**: {co_names}\n")

    lines.append("\n## Company Analysis\n")

    for v in us_valuations:
        name = v.get("company", "")
        cap = v.get("market_cap_usd")
        if cap and cap >= 1_000_000_000_000:
            cap_str = f"${cap / 1_000_000_000_000:.1f}T"
        elif cap and cap >= 1_000_000_000:
            cap_str = f"${cap / 1_000_000_000:.1f}B"
        elif cap:
            cap_str = f"${cap / 1_000_000:,.0f}M"
        else:
            cap_str = "N/A"
        summary_md = v.get("summary_md", "")

        # Escape markdown special chars in company name to prevent formatting breaks
        safe_name = _re.sub(r"([*_\[\]`\\])", r"\\\1", name)
        lines.append(f"### {safe_name} (Market Cap: {cap_str})\n")

        # Use first 15 lines of summary_md for brevity
        md_lines = summary_md.strip().split("\n")[:15]
        lines.append("\n".join(md_lines))
        lines.append("\n")

        # Add download link if available
        raw_url = v.get("download_url", "")
        download_url = raw_url if urlparse(raw_url).scheme in ("http", "https") else ""
        if download_url:
            lines.append(f"[📥 Download Full Excel Report]({download_url})\n")

        lines.append("\n---\n")

    lines.append(_DISCLAIMER)

    md_content = "\n".join(lines)
    # Strip script/iframe tags before markdown conversion (injection defence)
    md_content = _re.sub(
        r"<(script|iframe|object|embed|form)[^>]*>.*?</\1>",
        "",
        md_content,
        flags=_re.IGNORECASE | _re.DOTALL,
    )
    md_content = _re.sub(
        r"<(script|iframe|object|embed|form)[^>]*/?>",
        "",
        md_content,
        flags=_re.IGNORECASE,
    )
    html_content = markdown.markdown(md_content, extensions=["tables", "fenced_code"])
    return html_content


def _build_post_title(summary: dict) -> str:
    """Build post title from weekly summary label."""
    label = summary.get("label", "Weekly Report")
    return f"Weekly Valuation Report — {label}"


def post_to_wordpress(summary: dict) -> str | None:
    """Post weekly report to WordPress.com.

    Args:
        summary: The full _weekly_summary.json content.

    Returns:
        Post URL if successful, None otherwise.
    """
    site_url, username, password = _get_credentials()
    if not all([site_url, username, password]):
        logger.warning(
            "WP_SITE_URL, WP_USERNAME, or WP_APP_PASSWORD not set — skipping WordPress."
        )
        return None

    html_content = _build_post_content(summary)
    if not html_content:
        logger.info("No US-market companies to post — skipping WordPress.")
        return None

    title = _build_post_title(summary)
    endpoint = f"{site_url}/wp-json/wp/v2/posts"

    payload = {
        "title": title,
        "content": html_content,
        "status": "publish",
    }

    try:
        resp = requests.post(
            endpoint,
            json=payload,
            headers=_auth_header(username, password),
            timeout=30,
        )
        resp.raise_for_status()
        post_url = resp.json().get("link", "")
        logger.info("WordPress post published: %s", post_url)
        return post_url
    except requests.RequestException as e:
        logger.error("WordPress posting failed: %s", e)
        return None


def main() -> None:
    """CLI entry point for standalone testing."""
    parser = argparse.ArgumentParser(description="Post weekly report to WordPress")
    parser.add_argument(
        "--test", action="store_true", help="Test with latest summary JSON"
    )
    parser.add_argument("--summary-json", type=str, help="Path to _weekly_summary.json")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
    )

    if args.summary_json:
        summary_path = Path(args.summary_json)
    else:
        # Find latest weekly summary
        results_dir = Path(__file__).resolve().parent.parent / "valuation-results"
        summaries = sorted(results_dir.glob("*/_weekly_summary.json"), reverse=True)
        if not summaries:
            logger.error("No _weekly_summary.json found in valuation-results/")
            return
        summary_path = summaries[0]

    logger.info("Using summary: %s", summary_path)
    with open(summary_path, encoding="utf-8") as f:
        summary = json.load(f)

    if args.test:
        # Dry run: build content and save to file, don't post
        html = _build_post_content(summary)
        title = _build_post_title(summary)
        preview_path = summary_path.parent / "wp_preview.html"
        with open(preview_path, "w", encoding="utf-8") as f:
            f.write(f"<h1>{title}</h1>\n{html}")
        logger.info("Title: %s", title)
        logger.info("Content length: %d chars", len(html))
        logger.info("Preview saved: %s", preview_path)
        return

    url = post_to_wordpress(summary)
    if url:
        print(f"Published: {url}")
    else:
        print("Publishing failed or skipped.")


if __name__ == "__main__":
    main()
